{
 "title": "IoT Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "📡 Telemetry Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(iot_telemetry_sent_total[1m])",
     "legendFormat": "{{deviceId}} {{type}}"
    }
   ]
  },
  {
   "title": "⏱️ Telemetry Send Time (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(iot_telemetry_send_time_seconds_sum[1m]) / rate(iot_telemetry_send_time_seconds_count[1m])\r\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "🚨 Alerts Triggered (by severity)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (rate(iot_alerts_triggered_total[1m]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "✅ Successful Messages",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(iot_message_success_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "❌ Message Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(iot_message_errors_total[1m])",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "💾 Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "🧠 CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "100 - (avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "📀 Disk Usage (Used)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes - node_filesystem_free_bytes",
     "legendFormat": "Used - {{mountpoint}}"
    }
   ]
  }
 ]
}