simulator.lightbulb.enabled=false
simulator.temperature.enabled=false
simulator.smoke.enabled=false
simulator.energy.enabled=false
simulator.motion.enabled=false
simulator.fridge.enabled=false

simulator.retries=5
simulator.delay=2s
